n1=int(input ('Digite um número: '))
n2=int(input('Digite outro número: '))
#print(f'A soma entre o número {n1} e {n2} é {n1+n2}')
print(f'(Soma) {n1}+{n2}= {n1+n2}')
print(f'(Subtração) {n1}-{n2}= {n1-n2}')
print(f'(multiplicação) {n1}*{n2}= {n1*n2}')
print(f'(Divisão) {n1}/{n2}= {n1/n2}')
print(f'(Divisão inteira) {n1}//{n2}= {n1//n2}')
print(f'(Resto da divisão) {n1}%{n2}= {n1%n2}')
print(f'(Potenciação) {n1}^{n2}= {n1**n2}')
