num=int(input('Digite um número: '))
print(f'O dobro de {num} é  {num*2}')
print(f'O triplo de {num} e {num*3}')
print(f'{num} ao quadrado é {num**2}')
print(f'A raiz quadrada de {num} é {num**0.5}')